ansible_user: cto
rke2_version: v1.30.1+rke2r1
kube_vip_version: v0.8.0
cilium_version: v0.8.0
vip_address: 192.168.10.77
interface: eth0
rke2_token: kubernetesecretoken
rke2_ha_mode: true
rke2_api_ip: 192.168.10.77
rke2_servers_group_name: control_plane

