---
- name: Pre tasks
  hosts: all
  tasks:
    - name: Verify Ansible is version 2.11 or above
      assert:
        that:
          - ansible_version.full is version('2.11', '>=')

    - name: Ensure become_pass is empty
      assert:
        that:
          - ansible_become_pass is not defined

- name: Verify sudo functionality
  hosts: all
  tasks:
    - name: Check if user can run sudo commands
      command: whoami
      become: true

- name: Install RKE2 on master nodes
  hosts: masters
  roles:
    - install_rke2

- name: Configure kubeconfig
  hosts: masters
  tasks:
    - name: Ensure /etc/profile.d is writable
      file:
        path: /etc/profile.d
        state: directory
        owner: cto
        group: cto
        mode: '0755'

    - name: Create kubeconfig script
      copy:
        content: |
          export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
        dest: /etc/profile.d/kubeconfig.sh
        owner: cto
        group: cto
        mode: '0755'
        force: yes

- name: Install kubectl on master nodes
  hosts: masters
  tasks:
    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Verify kubectl installation
      command: kubectl version --client

- name: Deploy kube-vip
  hosts: masters
  roles:
    - deploy_kube_vip

- name: Deploy MetalLB
  hosts: all
  roles:
    - deploy_metallb

- name: Deploy Cilium
  hosts: all
  roles:
    - deploy_cilium

- name: Deploy Helm
  hosts: all
  roles:
    - deploy_helm

- name: Deploy Traefik
  hosts: all
  roles:
    - deploy_traefik

- name: Deploy Cert-Manager
  hosts: all
  roles:
    - deploy_cert-manager

- name: Deploy Rancher
  hosts: masters
  become: true
  tasks:
    - name: Add Helm repository for Rancher
      command:
        cmd: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
      changed_when: true

    - name: Update Helm repositories
      command:
        cmd: helm repo update
      changed_when: true

    - name: Install Cert-Manager
      command:
        cmd: |
          kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.crds.yaml
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace
      changed_when: true

    - name: Install Rancher
      command:
        cmd: helm install rancher rancher-latest/rancher \
          --namespace cattle-system \
          --set hostname=dash.imaginestack.net \
          --set ingress.tls.source=letsEncrypt \
          --set letsEncrypt.email={{ letsencrypt_email }}
      changed_when: true

- name: Verify RKE2 Cluster
  hosts: all
  tasks:
    - name: Check if cluster is up and running
      command: kubectl get nodes

- name: Join other masters to the cluster
  hosts: masters
  tasks:
    - name: Retrieve cluster token
      command: cat /var/lib/rancher/rke2/server/token
      register: token
      ignore_errors: true

    - name: Join master nodes to the cluster
      command: >
        /usr/local/bin/rke2 server --server https://{{ hostvars[groups['masters'][0]].ansible_host }}:9345 --token {{ token.stdout }}
      become: true
      when: token.stdout is defined

- name: Restart RKE2 server
  hosts: all
  tasks:
    - name: Restart RKE2 server
      service:
        name: rke2-server
        state: restarted

- name: Verify RKE2 Cluster
  hosts: all
  tasks:
    - name: Check if all nodes are Ready
      shell: kubectl get nodes
      register: result

    - name: Print node status
      debug:
        msg: "{{ result.stdout }}"

    - name: Check if kube-vip is running
      shell: kubectl get pods -n kube-system | grep kube-vip
      register: kube_vip_result

    - name: Print kube-vip status
      debug:
        msg: "{{ kube_vip_result.stdout }}"

    - name: Check if MetalLB is running
      shell: kubectl get pods -n metallb-system
      register: metallb_result

    - name: Print MetalLB status
      debug:
        msg: "{{ metallb_result.stdout }}"

    - name: Check if Cilium is running
      shell: kubectl get pods -n kube-system | grep cilium
      register: cilium_result

    - name: Print Cilium status
      debug:
        msg: "{{ cilium_result.stdout }}"

    - name: Check if Traefik is running
      shell: kubectl get pods -n kube-system | grep traefik
      register: traefik_result

    - name: Print Traefik status
      debug:
        msg: "{{ traefik_result.stdout }}"

    - name: Check if Cert-Manager is running
      shell: kubectl get pods -n cert-manager | grep cert-manager
      register: cert_manager_result

    - name: Print Cert-Manager status
      debug:
        msg: "{{ cert_manager_result.stdout }}"

    - name: Check if Rancher is running
      shell: kubectl get pods -n cattle-system | grep rancher
      register: rancher_result

    - name: Print Rancher status
      debug:
        msg: "{{ rancher_result.stdout }}"
