---
- name: Create MetalLB config directory
  ansible.builtin.file:
    path: /etc/metallb
    state: directory

- name: Install MetalLB
  ansible.builtin.shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
    kubectl create secret generic memberlist -n metallb-system --from-literal=secretkey="$(openssl rand -base64 128)"
  args:
    executable: /bin/bash

- name: Copy MetalLB config file
  ansible.builtin.template:
    src: metallb-config.yaml.j2
    dest: /etc/metallb/config.yaml

- name: Apply MetalLB configuration
  ansible.builtin.shell: kubectl apply -f /etc/metallb/config.yaml
  args:
    executable: /bin/bash
