---
- name: Install RKE2
  become: true
  script: /tmp/rke2_install.sh

- name: Enable RKE2 server
  become: true
  service:
    name: rke2-server
    enabled: yes

- name: Start RKE2 server
  become: true
  service:
    name: rke2-server
    state: started

- name: Ensure /etc/rancher/rke2 directory exists and is writable
  become: true
  file:
    path: /etc/rancher/rke2
    state: directory
    owner: cto
    group: cto
    mode: '0755'

- name: Configure RKE2
  become: true
  copy:
    content: |
      write your RKE2 configuration here
    dest: /etc/rancher/rke2/config.yaml
    owner: cto
    group: cto
    mode: '0644'

- name: Create kubeconfig file
  become: true
  copy:
    content: |
      write your kubeconfig content here
    dest: /etc/rancher/rke2/rke2.yaml
    owner: cto
    group: cto
    mode: '0644'
