---
- name: Download and install RKE2
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -

- name: Enable and start RKE2 server
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: yes

- name: Ensure kubeconfig file is created
  ansible.builtin.wait_for:
    path: /etc/rancher/rke2/rke2.yaml
    timeout: 300

- name: Set permissions for kubeconfig file
  ansible.builtin.file:
    path: /etc/rancher/rke2/rke2.yaml
    mode: '0644'

- name: Copy kubeconfig to default location
  ansible.builtin.copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Add k8s_cluster annotation to services
  vars:
    ansible_python_interpreter: /opt/ansible_venv/bin/python
  k8s_info:
    kind: Service
    namespace: kube-system
  register: services

- name: Patch services with k8s_cluster annotation
  vars:
    ansible_python_interpreter: /opt/ansible_venv/bin/python
  k8s:
    state: present
    definition: "{{ item }}"
  loop: "{{ services.resources | map(attribute='metadata') | map('combine', {'metadata': {'annotations': {'k8s_cluster': 'true'}}}}) }}"
