- name: Download and install RKE2
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{ rke2_version }} sh -
  args:
    creates: /usr/local/bin/rke2

- name: Enable and start RKE2 server
  systemd:
    name: rke2-server
    enabled: yes
    state: started

- name: Ensure kubeconfig file is created
  shell: |
    mkdir -p /etc/rancher/rke2
    /usr/local/bin/rke2 server --write-kubeconfig-mode 644 --write-kubeconfig /etc/rancher/rke2/rke2.yaml
  args:
    creates: /etc/rancher/rke2/rke2.yaml

- name: Set permissions for kubeconfig file
  file:
    path: /etc/rancher/rke2/rke2.yaml
    mode: '0644'

- name: Copy kubeconfig to default location
  shell: |
    mkdir -p $HOME/.kube
    cp /etc/rancher/rke2/rke2.yaml $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  when: ansible_user == 'cto'

- name: Add k8s_cluster annotation to services
  kubernetes.core.k8s_info:
    kind: Service
    namespace: kube-system
  register: k8s_services

- name: Annotate Kubernetes services with k8s_cluster
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ item.metadata.name }}"
        namespace: kube-system
        annotations:
          k8s_cluster: "{{ rke2_api_ip }}"
  with_items: "{{ k8s_services.resources }}"
  when: item.metadata.annotations.k8s_cluster is not defined
