---
- name: Create manifests directory
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: '0755'

- name: Create kube-vip Static Pod Manifest
  ansible.builtin.template:
    src: kube-vip-static-pod.yml.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml
    mode: '0644'

  