---
- name: Create manifests directory
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: '0755'

- name: Create kube-vip ConfigMap
  ansible.builtin.template:
    src: kube-vip-config.j2
    dest: /etc/kubernetes/manifests/kube-vip-config.yaml

- name: Apply kube-vip ConfigMap
  ansible.builtin.shell: kubectl apply -f /etc/kubernetes/manifests/kube-vip-config.yaml
  args:
    executable: /bin/bash

- name: Create kube-vip DaemonSet
  ansible.builtin.template:
    src: kube-vip-daemonset.yml.j2
    dest: /etc/kubernetes/manifests/kube-vip-daemonset.yaml

- name: Apply Kube-vip DaemonSet
  ansible.builtin.shell: kubectl apply -f /etc/kubernetes/manifests/kube-vip-daemonset.yaml
  args:
    executable: /bin/bash


