all:
  hosts:
    dash:
      ansible_host: 192.168.10.31
    rke2:
      ansible_host: 192.168.10.32
    rke3:
      ansible_host: 192.168.10.33
  children:
    control_plane:
      hosts:
        rke2-server1:
        rke2-server2:
        rke2-server3:
  vars:
    ansible_user: cto
    rke2_version: v1.30.1+rke2r1
    rke2_install_dir: "/usr/local/bin"
    rke2_binary_url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2.linux-amd64"
    kube_vip_version: v0.8.0
    cilium_version: v1.15.5
    traefik_version: 2.10.4
    vip_address: 192.168.10.77
    vip_interface: eth0
    rke2_token: kubernetesecretoken
    rke2_ha_mode: true
    rke2_ha_mode_kubevip: true
    rke2_api_ip: 192.168.10.77
    rke2_additional_sans:
      - 192.168.10.31
      - 192.168.10.32
      - 192.168.10.33
      - 192.168.10.77
    rke2_disable:
      - rke2-canal
    metallb_range: "192.168.10.60-70"
