
all:
  hosts:
    dash:
      ansible_host: 192.168.10.31
    rke2:
      ansible_host: 192.168.10.32
    rke3:
      ansible_host: 192.168.10.33
  children:
    masters:
      hosts:
        dash:
        rke2:
        rke3:
  vars:
    ansible_user: cto
    rke2_version: v1.30.1+rke2r1
    kube_vip_version: v0.3.7
    cilium_version: v1.11.5
    metallb_version: v0.11.0
    traefik_version: 2.5.4
    vip_address: 192.168.10.77
    interface: eth0
    rke2_token: kubernetesecretoken
    rke2_ha_mode: true
    rke2_ha_mode_kubevip: true
    rke2_api_ip: 192.168.10.77
    rke2_additional_sans:
      - "192.168.10.31"
      - "192.168.10.32"
      - "192.168.10.33"
      - "192.168.10.77"
    rke2_disable:
      - rke2-canal
    metallb_range: "192.168.10.60-70"

