---
- name: Deploy RKE2, Cilium, Kube-VIP, and MetalLB
  hosts: all
  become: true
  tasks:
    - name: Install dependencies on Debian-based systems
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - iproute2
        - ipset
        - curl
        - wget
        - python3-pip
        - python3-venv
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install dependencies on RedHat-based systems
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - iproute
        - ipset
        - curl
        - wget
        - python3-pip
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Create virtual environment
      ansible.builtin.command: python3 -m venv /opt/ansible_venv
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install kubernetes Python package in virtual environment
      ansible.builtin.command: /opt/ansible_venv/bin/pip install kubernetes
      when: ansible_facts['os_family'] == 'Debian'

- name: Configure Kube-VIP
  hosts: control_plane
  become: true
  roles:
    - role: kube-vip

- name: Install Cilium
  hosts: control_plane
  become: true
  roles:
    - role: cilium

- name: Configure MetalLB
  hosts: control_plane
  become: true
  roles:
    - role: metallb
