---
- name: Prepare Nodes
  hosts: all
  become: true
  vars_files:
    - inventories/hosts.yml
  roles:
    - role: prepare_nodes

- name: Debug Variables
  hosts: all
  tasks:
    - name: Print VIP Interface
      debug:
        msg: "VIP Interface: {{ interface }}"
    - name: Print VIP Address
      debug:
        msg: "VIP Address: {{ vip_address }}"

- name: Download RKE2
  hosts: all
  become: true
  roles:
    - role: rke2_download

- name: Prepare RKE2 Configuration
  hosts: control_plane
  become: true
  roles:
    - role: rke2_prepare

- name: Install Cilium
  hosts: control_plane
  become: true
  roles:
    - role: cilium

- name: Configure Kube-VIP
  hosts: control_plane
  become: true
  roles:
    - role: kube_vip


- name: Add servers to RKE2 cluster
  hosts: control_plane
  become: true
  roles:
    - role: add_server

- name: Apply additional manifests
  hosts: control_plane
  become: true
  roles:
    - role: apply_manifests
