---
- name: Deploy Traefik Ingress Controller
  hosts: masters
  become: true
  tasks:
    - name: Create Traefik values file
      template:
        src: "{{ playbook_dir }}/roles/deploy_traefik/templates/traefik-values.yml.j2"
        dest: /tmp/traefik-values.yml

    - name: Add Traefik Helm repository
      shell: |
        helm repo add traefik https://helm.traefik.io/traefik
        helm repo update

    - name: Install Traefik Helm chart
      shell: |
        helm install traefik traefik/traefik -f /tmp/traefik-values.yml

    - name: Wait for Traefik to be running
      shell: kubectl get pods -n kube-system -l app.kubernetes.io/name=traefik -o jsonpath="{.items[0].status.phase}"
      register: traefik_status
      until: traefik_status.stdout == "Running"
      retries: 10
      delay: 15
