---
- name: Deploy Cilium CNI
  hosts: masters
  become: true
  tasks:
    - name: Create Cilium values file
      template:
        src: "{{ playbook_dir }}/roles/deploy_cilium/templates/cilium-values.yml.j2"
        dest: /tmp/cilium-values.yml

    - name: Install Cilium
      shell: |
        helm repo add cilium https://helm.cilium.io/
        helm repo update
        helm install cilium cilium/cilium -f /tmp/cilium-values.yml --namespace kube-system

    - name: Wait for Cilium to be running
      shell: kubectl get pods -n kube-system -l k8s-app=cilium -o jsonpath="{.items[0].status.phase}"
      register: cilium_status
      until: cilium_status.stdout == "Running"
      retries: 10
      delay: 15
