---
- name: Install RKE2 on master nodes
  hosts: masters
  become: true
  tasks:
    - name: Download RKE2 installation script
      command: curl -sfL -o /tmp/rke2_install.sh https://get.rke2.io
      register: download_result

    - name: Make RKE2 installation script executable
      command: chmod +x /tmp/rke2_install.sh

    - name: Install RKE2
      command: bash /tmp/rke2_install.sh

    - name: Enable RKE2 server
      command: systemctl enable rke2-server

    - name: Start RKE2 server
      command: systemctl start rke2-server

    - name: Ensure /etc/rancher/rke2 directory exists
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Ensure rke2.yaml file exists and set permissions
      copy:
        dest: /etc/rancher/rke2/rke2.yaml
        content: |
          token: my-secret-token
          write-kubeconfig-mode: "0644"
          disable:
            - rke2-kube-proxy
          cni: cilium
      mode: '0644'

    - name: Ensure rke2-pss.yaml file exists and set permissions
      copy:
        dest: /etc/rancher/rke2/rke2-pss.yaml
        content: |
          # Policy settings for RKE2
      mode: '0644'
